"""Edit dashboard  models

Revision ID: 06e0aad78959
Revises: c89cb4bb99d1
Create Date: 2025-07-25 12:28:18.110048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e0aad78959'
down_revision = 'c89cb4bb99d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('layout_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('dashboard_widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('chart_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('chart_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('widget_name',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widget', schema=None) as batch_op:
        batch_op.alter_column('widget_name',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('order_index')
        batch_op.drop_column('is_active')
        batch_op.drop_column('chart_config')
        batch_op.drop_column('chart_data')
        batch_op.drop_column('widget_id')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('layout_config')
        batch_op.drop_column('is_active')

    op.create_table('user_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_sample_lables',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('label_type', sa.TEXT(), nullable=True),
    sa.Column('label_printed', sa.TEXT(), nullable=True),
    sa.Column('label_print_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_instrument_schedule',
    sa.Column('instrument_id', sa.TEXT(), nullable=True),
    sa.Column('instrument_name', sa.TEXT(), nullable=True),
    sa.Column('scheduled_by', sa.TEXT(), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=True),
    sa.Column('scheduled_date', sa.TEXT(), nullable=True),
    sa.Column('duration_hrs', sa.FLOAT(), nullable=True)
    )
    op.create_table('user_1_expiry_alerts',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True),
    sa.Column('alert_flag', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
