"""adding default value to feedback type

Revision ID: 0e26c368dd4b
Revises: 5636b013946a
Create Date: 2025-08-04 14:45:32.748888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e26c368dd4b'
down_revision = '5636b013946a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_column('feedback_rating')
        batch_op.add_column(sa.Column('feedback_rating', sa.String(length=10), nullable=True, server_default='neutral'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_2_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
