"""Adding dashboard configuration models

Revision ID: 0e47731fec09
Revises: 0dfd935a2753
Create Date: 2025-07-22 13:17:40.131032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e47731fec09'
down_revision = '0dfd935a2753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_id'), ['id'], unique=False)

    op.create_table('dashboard_widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('nl_query', sa.Text(), nullable=False),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('refresh_rate', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_widget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_widget_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_widget_id'))

    op.drop_table('dashboard_widget')
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_id'))

    op.drop_table('dashboard')
    # ### end Alembic commands ###
