"""Adding issues to query model and some more user details fields

Revision ID: 30f3816b1b64
Revises: 40e8b29baa5b
Create Date: 2025-08-21 18:44:04.293497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f3816b1b64'
down_revision = '40e8b29baa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issues', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_column('issues')

    op.create_table('user_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_2_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('label_type', sa.TEXT(), nullable=True),
    sa.Column('label_printed', sa.TEXT(), nullable=True),
    sa.Column('label_print_date', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
