"""creating chunk model for unstructured data storage

Revision ID: 3f07329e42b3
Revises: a533899e6571
Create Date: 2025-09-09 13:06:06.838799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f07329e42b3'
down_revision = 'a533899e6571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'file_chunks',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('file_metadata_id', sa.Integer, sa.ForeignKey('file_metadata.id'), nullable=False),
        sa.Column('agent_id', sa.Integer, sa.ForeignKey('agents.id'), nullable=True),
        sa.Column('chunk_index', sa.Integer, nullable=False),
        sa.Column('text', sa.Text, nullable=False),
        sa.Column('embedding_json', sa.JSON, nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False)
    )

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.String(length=10), nullable=True))
        batch_op.alter_column('table_metadata_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('table_metadata_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_type')
    # ### end Alembic commands ###
