"""Creating event table

Revision ID: 5259ea3a85c3
Revises: d099b8c8643b
Create Date: 2026-02-03 18:36:01.300976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5259ea3a85c3'
down_revision = 'd099b8c8643b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'event_fact',
        sa.Column('normalized_event_text', sa.Text(), nullable=True)
    )
    op.add_column(
        'event_fact',
        sa.Column('timestamp', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'event_fact',
        sa.Column('contains_overlast', sa.Boolean(), server_default=sa.false(), nullable=False)
    )

    # Optional: backfill normalized_event_text
    op.execute("""
        UPDATE event_fact
        SET normalized_event_text = event_text
        WHERE normalized_event_text IS NULL
    """)

    # ### end Alembic commands ###


def downgrade():
    op.drop_column('event_fact', 'contains_overlast')
    op.drop_column('event_fact', 'timestamp')
    op.drop_column('event_fact', 'normalized_event_text')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('org_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('org_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
