"""Adding soft delete to datasources and uploaded files

Revision ID: 5dee0c0c6e46
Revises: dbba77b79669
Create Date: 2025-12-18 16:17:44.795886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dee0c0c6e46'
down_revision = 'dbba77b79669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True))

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(),server_default='false', nullable=True))

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True))

    with op.batch_alter_table('table_of_uploadedfiles_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_of_uploadedfiles_metadata', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    op.create_table('user_1_sample_lables',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('label_type', sa.TEXT(), nullable=True),
    sa.Column('label_printed', sa.TEXT(), nullable=True),
    sa.Column('label_print_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_expiry_alerts',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True),
    sa.Column('alert_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_jeron',
    sa.Column('naam', sa.TEXT(), nullable=True),
    sa.Column('datum', sa.TEXT(), nullable=True),
    sa.Column('duur', sa.BIGINT(), nullable=True),
    sa.Column('deelmissie', sa.TEXT(), nullable=True),
    sa.Column('programmeur_specialist', sa.TEXT(), nullable=True),
    sa.Column('uitvoerders', sa.TEXT(), nullable=True),
    sa.Column('regio', sa.TEXT(), nullable=True),
    sa.Column('vestiging', sa.TEXT(), nullable=True),
    sa.Column('soort_locatie', sa.TEXT(), nullable=True),
    sa.Column('kernfunctie', sa.TEXT(), nullable=True),
    sa.Column('categorie', sa.TEXT(), nullable=True),
    sa.Column('aantal_deelnemers', sa.BIGINT(), nullable=True),
    sa.Column('aantal_online_deelnemers', sa.BIGINT(), nullable=True),
    sa.Column('onderzoek', sa.TEXT(), nullable=True),
    sa.Column('link_onderzoek', sa.TEXT(), nullable=True),
    sa.Column('geannuleerd', sa.TEXT(), nullable=True),
    sa.Column('verplaatst', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_instrument_schedule',
    sa.Column('instrument_id', sa.TEXT(), nullable=True),
    sa.Column('instrument_name', sa.TEXT(), nullable=True),
    sa.Column('scheduled_by', sa.TEXT(), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=True),
    sa.Column('scheduled_date', sa.TEXT(), nullable=True),
    sa.Column('duration_hrs', sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
