"""Updating Agent model for using unstructured query

Revision ID: 712a08e8a4a6
Revises: 3f07329e42b3
Create Date: 2025-09-11 18:52:24.066493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712a08e8a4a6'
down_revision = '3f07329e42b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rag_system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rag_task', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rag_instruction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agent_type', sa.String(length=20), nullable=False, server_default='structured'))
        batch_op.alter_column('sql_system_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sql_task',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sql_instruction',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('original_filename',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.TEXT(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=False)

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('sql_instruction',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('sql_task',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('sql_system_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('agent_type')
        batch_op.drop_column('rag_instruction')
        batch_op.drop_column('rag_task')
        batch_op.drop_column('rag_system_prompt')

    op.create_table('user_1_instrument_schedule',
    sa.Column('instrument_id', sa.TEXT(), nullable=True),
    sa.Column('instrument_name', sa.TEXT(), nullable=True),
    sa.Column('scheduled_by', sa.TEXT(), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=True),
    sa.Column('scheduled_date', sa.TEXT(), nullable=True),
    sa.Column('duration_hrs', sa.FLOAT(), nullable=True)
    )
    op.create_table('user_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_expiry_alerts',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True),
    sa.Column('alert_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_sample_lables',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('label_type', sa.TEXT(), nullable=True),
    sa.Column('label_printed', sa.TEXT(), nullable=True),
    sa.Column('label_print_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
