"""adding event date to  event table

Revision ID: 7a889ed2c5de
Revises: a8d8a1ef0299
Create Date: 2026-02-17 21:35:22.961871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a889ed2c5de'
down_revision = 'a8d8a1ef0299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('event_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('event_datetime', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_fact_event_datetime'), ['event_datetime'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_event_fact_event_datetime'))
        batch_op.drop_column('category')
        batch_op.drop_column('event_datetime')
        batch_op.drop_column('event_time')
        batch_op.drop_column('event_date')

    op.create_table('org_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('org_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('org_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
