"""Adding soft delete to agent model

Revision ID: 81fed14d4111
Revises: 5dee0c0c6e46
Create Date: 2025-12-19 12:12:14.867538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fed14d4111'
down_revision = '5dee0c0c6e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.alter_column('source_name',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('source_type',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('connection_status',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('host',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('port',
               existing_type=sa.TEXT(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('server',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('database',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('driver',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('snowflake_account',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('snowflake_warehouse',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('snowflake_schema',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_access_key',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_secret_key',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_region',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('s3_bucket',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_prefix',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('sqlite_path',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('original_filename',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.TEXT(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('table_of_uploadedfiles_metadata', schema=None) as batch_op:
        batch_op.alter_column('table_name',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_of_uploadedfiles_metadata', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('table_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=False)

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('file_size',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=False)

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.alter_column('sqlite_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_prefix',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_bucket',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('s3_secret_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_access_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('snowflake_schema',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('snowflake_warehouse',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('snowflake_account',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('driver',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('database',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('server',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('port',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
        batch_op.alter_column('host',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('connection_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)
        batch_op.alter_column('source_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=False)
        batch_op.alter_column('source_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
