"""mapping user_id with businessglossary

Revision ID: 872992389bb0
Revises: df1074d65f7c
Create Date: 2025-08-09 16:43:39.048607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872992389bb0'
down_revision = 'df1074d65f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_glossary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_business_glossary_user',  # <-- give a name
            'user',                       # target table
            ['user_id'],                  # local column(s)
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_glossary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_1_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    op.create_table('user_2_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
