"""adding language column to metadata table

Revision ID: a8d8a1ef0299
Revises: 5259ea3a85c3
Create Date: 2026-02-13 11:55:56.305079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d8a1ef0299'
down_revision = '5259ea3a85c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_column('language')

    op.create_table('org_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('org_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('org_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
