"""Adding vectoe embeddings for feedback loop

Revision ID: b4a20eab4182
Revises: 06e0aad78959
Create Date: 2025-08-01 21:46:50.713924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a20eab4182'
down_revision = '06e0aad78959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_query_embedding', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('response_embedding', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('feedback_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_embedding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_column('feedback_embedding')
        batch_op.drop_column('feedback')
        batch_op.drop_column('feedback_type')
        batch_op.drop_column('response_embedding')
        batch_op.drop_column('user_query_embedding')

    op.create_table('user_1_expiry_alerts',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True),
    sa.Column('alert_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_instrument_schedule',
    sa.Column('instrument_id', sa.TEXT(), nullable=True),
    sa.Column('instrument_name', sa.TEXT(), nullable=True),
    sa.Column('scheduled_by', sa.TEXT(), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=True),
    sa.Column('scheduled_date', sa.TEXT(), nullable=True),
    sa.Column('duration_hrs', sa.FLOAT(), nullable=True)
    )
    op.create_table('user_1_Co2',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr3', sa.TEXT(), nullable=True),
    sa.Column('book_attr5', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('mkt1', sa.TEXT(), nullable=True),
    sa.Column('comp1', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('bucket_start', sa.TEXT(), nullable=True),
    sa.Column('bucket_end', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.BIGINT(), nullable=True),
    sa.Column('volume', sa.TEXT(), nullable=True),
    sa.Column('mktval', sa.TEXT(), nullable=True),
    sa.Column('trdval', sa.TEXT(), nullable=True),
    sa.Column('trdprc', sa.FLOAT(), nullable=True)
    )
    op.create_table('user_1_samples',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('test_required', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('current_location', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('final_disposal_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_inventory_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_sample_lables',
    sa.Column('sample_id', sa.TEXT(), nullable=True),
    sa.Column('label_type', sa.TEXT(), nullable=True),
    sa.Column('label_printed', sa.TEXT(), nullable=True),
    sa.Column('label_print_date', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_stock_thresholds',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('current_stock', sa.BIGINT(), nullable=True),
    sa.Column('threshold_limit', sa.BIGINT(), nullable=True),
    sa.Column('reorder_flag', sa.TEXT(), nullable=True)
    )
    op.create_table('user_1_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
