"""Edit dashboard widgiet model

Revision ID: c89cb4bb99d1
Revises: 0e47731fec09
Create Date: 2025-07-22 19:04:27.459389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89cb4bb99d1'
down_revision = '0e47731fec09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sql_query', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('widget_name', sa.String(), nullable=True))
        batch_op.alter_column('nl_query',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widget', schema=None) as batch_op:
        batch_op.alter_column('nl_query',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('sql_query')

    # ### end Alembic commands ###
