"""Creating Entity layer above user

Revision ID: d400292fa00d
Revises: 81fed14d4111
Create Date: 2025-12-26 17:00:11.154111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd400292fa00d'
down_revision = '81fed14d4111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True, server_default='free'),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, server_default='active'))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_organization_id', 'organizations', ['organization_id'], ['id'])
        batch_op.drop_column('is_active')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(
            'fk_user_organization_id',   # 👈 MUST MATCH UPGRADE
            type_='foreignkey'
        )
        batch_op.drop_column('organization_id')
        batch_op.drop_column('last_login')
        batch_op.drop_column('status')

    op.drop_table('organizations')
    # ### end Alembic commands ###
