"""Creating connections between Org and other table

Revision ID: dad335c58630
Revises: be125fb54d97
Create Date: 2026-01-02 14:57:21.346116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad335c58630'
down_revision = 'be125fb54d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_agents_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_dashboard_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_data_source_connections_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_file_metadata_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_query_logs_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('table_of_uploadedfiles_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_table_of_uploadedfiles_metadata_organization_id', 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_of_uploadedfiles_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('data_source_connections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
