"""Changes to User table

Revision ID: dadd94471557
Revises: dad335c58630
Create Date: 2026-01-06 15:48:39.695921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadd94471557'
down_revision = 'dad335c58630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=50), nullable=True))
        batch_op.drop_column('role_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
