"""Add Business glossary model

Revision ID: df1074d65f7c
Revises: 0e26c368dd4b
Create Date: 2025-08-08 20:44:13.421172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1074d65f7c'
down_revision = '0e26c368dd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_2_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    op.create_table('business_glossary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(length=255), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_1_Power',
    sa.Column('report_date', sa.TEXT(), nullable=True),
    sa.Column('book', sa.TEXT(), nullable=True),
    sa.Column('book_attr6', sa.TEXT(), nullable=True),
    sa.Column('book_attr7', sa.TEXT(), nullable=True),
    sa.Column('book_attr8', sa.TEXT(), nullable=True),
    sa.Column('usr_val4', sa.TEXT(), nullable=True),
    sa.Column('tgroup1', sa.TEXT(), nullable=True),
    sa.Column('tgroup2', sa.TEXT(), nullable=True),
    sa.Column('segment', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('bucket', sa.TEXT(), nullable=True),
    sa.Column('horizon', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('volume_bl', sa.TEXT(), nullable=True),
    sa.Column('volume_pk', sa.TEXT(), nullable=True),
    sa.Column('volume_ofpk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_bl', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_pk', sa.TEXT(), nullable=True),
    sa.Column('mkt_val_ofpk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_bl', sa.TEXT(), nullable=True),
    sa.Column('trd_val_pk', sa.TEXT(), nullable=True),
    sa.Column('trd_val_ofpk', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
