from flask import Blueprint
from app.controllers import agent_controller, dashboard_controller, data_controller, graph_controller, profile_controller, query_controller

profile_bp = Blueprint('profile_bp', __name__)
profile_bp.route('/me', methods=['GET'])(profile_controller.get_user_profile)
profile_bp.route('/user', methods=['PUT'])(profile_controller.update_user_profile)
profile_bp.route('/tour/complete', methods=['POST'])(profile_controller.complete_tour)
profile_bp.route('/tour/reset', methods=['POST'])(profile_controller.reset_tour)
profile_bp.route('/setup-progress', methods=['GET'])(profile_controller.get_setup_progress)

org_bp = Blueprint('org_bp', __name__)
org_bp.route('/setup', methods=['POST'])(profile_controller.post_organization_setup)
org_bp.route('/users', methods=['GET'])(profile_controller.get_org_users)
org_bp.route('/users/invite', methods=['POST'])(profile_controller.invite_user)
org_bp.route('/users/<id>', methods=['PUT'])(profile_controller.update_user)
org_bp.route('/users/<id>', methods=['DELETE'])(profile_controller.remove_user)
org_bp.route('/users/bulk-update-role', methods=['POST'])(profile_controller.bulk_update_role)
org_bp.route('/users/bulk-remove', methods=['POST'])(profile_controller.bulk_remove_users)
org_bp.route('/users/bulk-resend-invites', methods=['POST'])(profile_controller.bulk_resend_invites)


data_bp = Blueprint('data_bp', __name__)
data_bp.route('/save-connection', methods=['POST'])(data_controller.save_connection)
data_bp.route('/test-connection', methods=['POST'])(data_controller.test_connection)
data_bp.route('/get-data-sources', methods=['GET'])(data_controller.get_data_sources)
data_bp.route('/get-data-source/<int:connection_id>', methods=['GET'])(data_controller.get_data_source)
data_bp.route('/update-connection/<int:connection_id>', methods=['PUT'])(data_controller.edit_connection)
data_bp.route("/test-saved-connection/<int:source_id>", methods=["POST"])(data_controller.test_saved_connection)
data_bp.route('/upload-file', methods=['POST'])(data_controller.handle_file_upload)
data_bp.route('/get-uploaded-files', methods=['GET'])(data_controller.get_uploaded_files)
data_bp.route('/get-existing-tables', methods=['GET'])(data_controller.get_existing_tables)
data_bp.route('/delete-connection/<int:connection_id>', methods=['DELETE'])(data_controller.delete_connection)
data_bp.route('/delete-file/<int:file_id>', methods=['DELETE'])(data_controller.delete_file)
data_bp.route('/s3/<int:connection_id>/objects', methods=['GET'])(data_controller.list_s3_objects)
data_bp.route('/s3/<int:connection_id>/import', methods=['POST'])(data_controller.import_s3_objects)
data_bp.route('/jobs', methods=['GET'])(data_controller.list_ingestion_jobs)
data_bp.route('/jobs/<int:job_id>', methods=['GET'])(data_controller.get_ingestion_job)

agent_bp = Blueprint("agent_bp", __name__)
agent_bp.route("/create", methods=["POST"])(agent_controller.create_agent)
agent_bp.route("/get-agents", methods=["GET"])(agent_controller.get_agents)
agent_bp.route("/get/<int:agent_id>", methods=["GET"])(agent_controller.get_agent)
agent_bp.route("/update/<int:agent_id>", methods=["PUT"])(agent_controller.update_agent)
agent_bp.route("/delete/<int:agent_id>", methods=["DELETE"])(agent_controller.delete_agent)
agent_bp.route("/generate-prompts", methods=["POST"])(agent_controller.generate_prompts) 
agent_bp.route("/glossary/create", methods=["POST"])(agent_controller.add_glossary)
agent_bp.route('/glossary/<int:item_id>', methods=['GET'])(agent_controller.get_glossary)
agent_bp.route('/glossary/bulk-upload', methods=['POST'])(agent_controller.upload_glossary)
agent_bp.route('/glossary/list', methods=['GET'])(agent_controller.get_glossarys)
agent_bp.route('/glossary/delete/<int:item_id>', methods=['DELETE'])(agent_controller.delete_glossary)
agent_bp.route('/stats', methods=['GET'])(agent_controller.get_stats)
agent_bp.route("/files", methods=["GET"])(agent_controller.get_files)

query_bp = Blueprint("query_bp", __name__)
query_bp.route("/copilot/<agent_id>", methods=["POST"])(query_controller.copilot_query_agent)
query_bp.route("/feedback/submit", methods=["POST"])(query_controller.submit_feedback)
query_bp.route("/graph/<agent_id>", methods=["POST"])(graph_controller.graph_query_controller)
query_bp.route("/graph/sqltograph/<agent_id>", methods=["POST"])(graph_controller.sql_graph_controller)
query_bp.route("/graph/drilldown", methods=["POST"])(graph_controller.graph_drilldown_controller)
query_bp.route("/logs", methods=["GET"])(query_controller.fetch_query_logs)

dashboard_bp = Blueprint("dashboard_bp", __name__)
dashboard_bp.route('/<int:dashboard_id>', methods=['GET'])(dashboard_controller.get_dashboard)
dashboard_bp.route("/create", methods=["POST"])(dashboard_controller.create_dashboard)
dashboard_bp.route('edit/<int:dashboard_id>', methods=['PUT'])(dashboard_controller.edit_dashboard)
dashboard_bp.route('/<int:dashboard_id>/widget', methods=['POST'])(dashboard_controller.create_widget)
dashboard_bp.route('/<int:dashboard_id>/widgets/bulk-save', methods=['POST'])(dashboard_controller.bulk_save_widgets)
dashboard_bp.route('/<int:dashboard_id>/widget/<widget_id>', methods=['DELETE'])(dashboard_controller.delete_widget)
dashboard_bp.route('/<int:dashboard_id>/layout', methods=['PUT'])(dashboard_controller.update_dashboard_layout)
dashboard_bp.route('/list', methods=['GET'])(dashboard_controller.get_user_dashboards)
dashboard_bp.route('/update/<int:dashboard_id>', methods=['PUT'])(dashboard_controller.update_dashboard)
dashboard_bp.route('/delete/<int:dashboard_id>', methods=['DELETE'])(dashboard_controller.delete_dashboard)
dashboard_bp.route('/api/dashboard/widget/<int:widget_id>/data', methods=['GET'])(dashboard_controller.get_widget_data)
dashboard_bp.route('/<int:dashboard_id>/widgets', methods=['GET'])(dashboard_controller.list_widgets)

